/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.view;

/**
 *
 * @author Ismael Travez, The Java Bandits, DCCO-ESPE
 */
public class FrmMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMainMenu
     */
    public FrmMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btRealizarPedido = new javax.swing.JButton();
        btDejarComentario = new javax.swing.JToggleButton();
        btModoAdmin = new javax.swing.JToggleButton();
        btVerMenu = new javax.swing.JToggleButton();
        btUbicacion = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitmLeaveOrder = new javax.swing.JMenuItem();
        mitmLeaveComment = new javax.swing.JMenuItem();
        mitmShowMenu = new javax.swing.JMenuItem();
        mitmShowLocation = new javax.swing.JMenuItem();
        btnAdminMode = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGACHADITOS DE LA JAVI");

        btRealizarPedido.setText("Realizar Pedido");
        btRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRealizarPedidoActionPerformed(evt);
            }
        });

        btDejarComentario.setText("Dejar un comentario");
        btDejarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDejarComentarioActionPerformed(evt);
            }
        });

        btModoAdmin.setText("Modo Administracion");
        btModoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModoAdminActionPerformed(evt);
            }
        });

        btVerMenu.setText("Ver Menu");
        btVerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerMenuActionPerformed(evt);
            }
        });

        btUbicacion.setText("Ubicacion");
        btUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbicacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDejarComentario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRealizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btModoAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btVerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRealizarPedido)
                .addGap(18, 18, 18)
                .addComponent(btDejarComentario)
                .addGap(18, 18, 18)
                .addComponent(btModoAdmin)
                .addGap(18, 18, 18)
                .addComponent(btVerMenu)
                .addGap(18, 18, 18)
                .addComponent(btUbicacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Cliente");

        mitmLeaveOrder.setText("Realizar Pedido");
        mitmLeaveOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmLeaveOrderActionPerformed(evt);
            }
        });
        jMenu1.add(mitmLeaveOrder);

        mitmLeaveComment.setText("Dejar un Comentario");
        mitmLeaveComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmLeaveCommentActionPerformed(evt);
            }
        });
        jMenu1.add(mitmLeaveComment);

        mitmShowMenu.setText("Ver Menú");
        jMenu1.add(mitmShowMenu);

        mitmShowLocation.setText("Ubicación");
        jMenu1.add(mitmShowLocation);

        jMenuBar1.add(jMenu1);

        btnAdminMode.setText("Modo Administración");
        jMenuBar1.add(btnAdminMode);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRealizarPedidoActionPerformed
        new FrmMenuOrder().setVisible(true);
        dispose();
    }//GEN-LAST:event_btRealizarPedidoActionPerformed

    private void btModoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModoAdminActionPerformed
        new FrmAdminLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btModoAdminActionPerformed

    private void btDejarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDejarComentarioActionPerformed
        new FrmMakeComent().setVisible(true);
        dispose();
    }//GEN-LAST:event_btDejarComentarioActionPerformed

    private void btVerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerMenuActionPerformed
        new FrmDishList().setVisible(true);
        dispose();
    }//GEN-LAST:event_btVerMenuActionPerformed

    private void btUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbicacionActionPerformed
        new FrmLocation().setVisible(true);
        dispose();
    }//GEN-LAST:event_btUbicacionActionPerformed

    private void mitmLeaveOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmLeaveOrderActionPerformed
        new FrmMenuOrder().setVisible(true);
        dispose();
    }//GEN-LAST:event_mitmLeaveOrderActionPerformed

    private void mitmLeaveCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmLeaveCommentActionPerformed
       new FrmMakeComent().setVisible(true);
       dispose();
    }//GEN-LAST:event_mitmLeaveCommentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btDejarComentario;
    private javax.swing.JToggleButton btModoAdmin;
    private javax.swing.JButton btRealizarPedido;
    private javax.swing.JToggleButton btUbicacion;
    private javax.swing.JToggleButton btVerMenu;
    private javax.swing.JMenu btnAdminMode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mitmLeaveComment;
    private javax.swing.JMenuItem mitmLeaveOrder;
    private javax.swing.JMenuItem mitmShowLocation;
    private javax.swing.JMenuItem mitmShowMenu;
    // End of variables declaration//GEN-END:variables
}
