/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import controladores.ConexionMongo;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author antho
 */
public class vista_verfactura extends javax.swing.JFrame {

    private String cedulaCliente;
    
    public vista_verfactura(String cedulaCliente) {
        this.setLocationRelativeTo(null);
        this.cedulaCliente = cedulaCliente;
        initComponents();
        cargarDatos();
    }
    
    public void cargarDatos(){

        // Realizar la consulta a la base de datos
        MongoDatabase database = ConexionMongo.getDatabase();

        if (database == null) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        MongoCollection<Document> ordenesCollection = database.getCollection("ordenes");
        MongoCollection<Document> comidaCollection = database.getCollection("comida");

        Document query = new Document("cedulaCliente", cedulaCliente);  // Usamos la cédula obtenida
        Document orden = ordenesCollection.find(query).first();

        jTextArea1.setText("");  // Limpiar el área de texto

        if (orden != null) {
            String nombreCliente = orden.getString("nombreCliente");
            String cedulaCliente = orden.getString("cedulaCliente");
            String telefonoCliente = orden.getString("telefonoCliente");
            String direccionCliente = orden.getString("direccionCliente");
            String correoCliente = orden.getString("correoCliente");
            LocalDateTime fecha = LocalDateTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String fechaFormateada = fecha.format(formatter);

            List<Document> platillos = (List<Document>) orden.get("platillos");
            double total = 0;
            StringBuilder detalles = new StringBuilder();
            detalles.append("Detalles del Pedido:\n");

            for (Document platillo : platillos) {
                String nombrePlatillo = platillo.getString("nombre");
                int cantidad = platillo.getInteger("cantidad");
                Document comida = comidaCollection.find(new Document("Nombre", nombrePlatillo)).first();
                if (comida != null) {
                    String descripcion = comida.getString("Descripcion");
                    double precio;

                    // Verificar y convertir el tipo de dato de "Precio"
                    if (comida.get("Precio") instanceof Integer) {
                        precio = ((Integer) comida.get("Precio")).doubleValue();
                    } else {
                        precio = comida.getDouble("Precio");
                    }

                    double subtotal = precio * cantidad;
                    total += subtotal;
                    detalles.append(String.format("Nombre: %s, Descripcion: %s, Precio: %.2f, Cantidad: %d\n", nombrePlatillo, descripcion, precio, cantidad));
                }
            }
            String factura = String.format(
                    "FACTURA\n-------------------------------------------\n" +
                    "Informacion del Cliente:\n" +
                    "Nombre: %s\n" +
                    "Cedula: %s\n" +
                    "Telefono: %s\n" +
                    "Direccion: %s\n" +
                    "Correo: %s\n" +
                    "Fecha: %s\n" +
                    "-------------------------------------------\n" +
                    "%s" +
                    "-------------------------------------------\n" +
                    "Total: $%.2f",
                    nombreCliente, cedulaCliente, telefonoCliente, direccionCliente, correoCliente, fechaFormateada, detalles.toString(), total);

            jTextArea1.setText(factura);
        } else {
            jTextArea1.setText("No se encontraron órdenes para la cédula ingresada.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 102, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton5.setBackground(new java.awt.Color(0, 51, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Atras");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new vista_factura().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_verfactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_verfactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_verfactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_verfactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Llamamos al constructor de vista_metodopago con una cedula de ejemplo (puedes cambiarla)
                String cedula = "1234567890";  // La cédula que quieras enviar
                new vista_metodopago(cedula).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
